using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OrbitBook.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FixIdentitySequences : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""BOOKINGS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""USERS_ORBIT"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""DESTINATIONS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""PASSENGERS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""PAYMENTS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""REVIEWS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""BOOKING_STATUSES"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""ROLES"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""DESTINATION_TYPES"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
            migrationBuilder.Sql(@"ALTER TABLE ""AI_RECOMMENDATIONS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""BOOKINGS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""USERS_ORBIT"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""DESTINATIONS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""PASSENGERS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""PAYMENTS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""REVIEWS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""BOOKING_STATUSES"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""ROLES"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""DESTINATION_TYPES"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
            migrationBuilder.Sql(@"ALTER TABLE ""AI_RECOMMENDATIONS"" MODIFY ""Id"" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
        }
    }
}
