// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitBook.Infrastructure.Data;

#nullable disable

namespace OrbitBook.Infrastructure.Migrations
{
    [DbContext(typeof(OrbitBookDbContext))]
    [Migration("20260609022946_AddSeedDataWithAdmin")]
    partial class AddSeedDataWithAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitBook.Domain.Entities.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DestinationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PromptUsed")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("AI_RECOMMENDATIONS", (string)null);
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumPassengers")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("StatusId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("BOOKINGS", (string)null);
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("BOOKING_STATUSES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Reserva criada aguardando confirmação de pagamento",
                            Name = "PENDENTE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pagamento aprovado e reserva confirmada",
                            Name = "CONFIRMADO"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Missão em andamento — viajante em trânsito",
                            Name = "EM_MISSAO"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Missão concluída com sucesso e retorno confirmado",
                            Name = "CONCLUIDO"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Reserva cancelada pelo viajante ou pela operadora",
                            Name = "CANCELADO"
                        });
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("DistanceKm")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TypeId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("DESTINATIONS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 6,
                            BasePrice = 450000m,
                            Capacity = 6,
                            Description = "Voo suborbital de 11 minutos.",
                            DistanceKm = 107L,
                            ImageUrl = "https://orbitbook.com/img/new-shepard.jpg",
                            Name = "Blue Origin New Shepard",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 4,
                            BasePrice = 350000m,
                            Capacity = 4,
                            Description = "Voo suborbital com decolagem por aeronave.",
                            DistanceKm = 88L,
                            ImageUrl = "https://orbitbook.com/img/vss-unity.jpg",
                            Name = "Virgin Galactic VSS Unity",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 4,
                            BasePrice = 55000000m,
                            Capacity = 4,
                            Description = "Estadia de 14 dias na primeira estação espacial.",
                            DistanceKm = 420L,
                            ImageUrl = "https://orbitbook.com/img/axiom-station.jpg",
                            Name = "Axiom Station Ax-4",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 4,
                            BasePrice = 35000000m,
                            Capacity = 4,
                            Description = "Missão de 7 dias em órbita baixa.",
                            DistanceKm = 380L,
                            ImageUrl = "https://orbitbook.com/img/crew-dragon.jpg",
                            Name = "SpaceX Crew Dragon LEO",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 3,
                            BasePrice = 40000000m,
                            Capacity = 3,
                            Description = "Parceria internacional para estadia de 10 dias.",
                            DistanceKm = 390L,
                            ImageUrl = "https://orbitbook.com/img/tiangong.jpg",
                            Name = "Estação Orbital Chinesa Tiangong",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 2,
                            BasePrice = 150000000m,
                            Capacity = 2,
                            Description = "Missão de 8 dias ao redor da Lua sem pouso.",
                            DistanceKm = 384400L,
                            ImageUrl = "https://orbitbook.com/img/artemis-flyby.jpg",
                            Name = "Artemis Lunar Flyby",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 2,
                            BasePrice = 250000000m,
                            Capacity = 2,
                            Description = "Pouso na superfície lunar por 5 dias.",
                            DistanceKm = 384400L,
                            ImageUrl = "https://orbitbook.com/img/lunar-gateway.jpg",
                            Name = "Missão Lunar Gateway Alpha",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 12,
                            BasePrice = 500000000m,
                            Capacity = 12,
                            Description = "Missão pioneira de 2 anos para colonização.",
                            DistanceKm = 225000000L,
                            ImageUrl = "https://orbitbook.com/img/mars-colony.jpg",
                            Name = "SpaceX Mars Colony — Alpha Wave",
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.DestinationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("DESTINATION_TYPES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Voo acima de 100km com experiência de microgravidade por até 30 minutos",
                            Name = "SUBORBITAL"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Órbita baixa terrestre entre 350km e 420km de altitude",
                            Name = "ORBITA_LEO"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Missões para flyby ou pouso na superfície lunar",
                            Name = "LUNAR"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Missões de longa duração para colonização de Marte",
                            Name = "MARCIANO"
                        });
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("BookingId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MedicalStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("PASSENGERS", (string)null);
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("PAYMENTS", (string)null);
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Rating")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("REVIEWS", (string)null);
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Usuário final que busca e reserva experiências espaciais",
                            Name = "VIAJANTE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Administrador com acesso total à plataforma OrbitBook",
                            Name = "ADMIN"
                        });
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PassengerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TicketClass")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("USERS_ORBIT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentNumber = "00000000000",
                            Email = "admin@orbitbook.com",
                            Name = "Admin OrbitBook",
                            PasswordHash = "$2a$11$/tKJLtMjYT4LSSfGaiFdyOM6X5fnzM1q1vEMEacM0uReqC2Wsg1sG",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.AiRecommendation", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("OrbitBook.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Booking", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.Destination", "Destination")
                        .WithMany("Bookings")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitBook.Domain.Entities.BookingStatus", "Status")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitBook.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Destination", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.DestinationType", "Type")
                        .WithMany("Destinations")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Passenger", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Payment", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("OrbitBook.Domain.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Review", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("OrbitBook.Domain.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitBook.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitBook.Domain.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.User", b =>
                {
                    b.HasOne("OrbitBook.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("Payment");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.DestinationType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OrbitBook.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
